### ISSUE TITLE
Incorrect check in setup.py for pysteam 1.0.0-b2

### ISSUE THREAD

**Issue by ProfessorKaos64** [scottrice/pysteam#5]
Your 1.0.0-b2 package on pypi containts:

```
version='1.0.0-beta2'
```

This conflicts with the b2 in requirements.txt. Once corrected to b2 in the version line, it will work.

Corrected package (of course I can't change your b2):
https://pypi.python.org/pypi/pysteam-steamos/1.0.0-b2

See:
https://github.com/scottrice/pysteam/pull/6

**Comment by scottrice** [comment]
Huh, its odd that this isnt working for you. Ice uses `b2` in it's `setup.py` and it works fine (https://github.com/scottrice/Ice/blob/master/requirements.txt#L3).

I'm not super familiar with Python packaging though, so I'll take your word for it.

**Comment by scottrice** [comment]
Fixed by #6

**Comment by mdeguzis** [comment]
Yea it complains if you parse requirements.txt, which has b2, but the b2 you originally had, has beta2\* in it's pkg info.

**Comment by mdeguzis** [comment]
Did you add this yet to pypi ? I can't upload a different version since it's under your name.
